### ISSUE TITLE
Mykhailo

### ISSUE THREAD

**Issue by work70727** [deancasey411/webtraderpro#1]

**Comment by mykhailoananiev23** [comment]
https://www.loom.com/share/3eac47deb9d941769f5891380a535493

please check this video.

**Comment by mykhailoananiev23** [comment]
> Hello, Dean
> 
> How are you?
> 
> I am really sorry to inform you that my account has been blocked. After sending you last message from Upwork, my account was blocked. So I couldn't access Upwork and couldn't see any message and cancelled my all contract at the moment. Maybe you can get refund money($800) for my work. Certainly, I am sure about that.
> 
> As I write you in my last message, I've already completed lot's of thing as you mentioned. At the moment, I am trying to work chart part. And then I have no progress as your api is not working now. If you fix api bug, I can finish this part soon, I think.
> 
> I think, you are satisficed with my work and have some stuff to fix and update for your demo and future's works.
> 
> So I hope to discuss about your task via third-party message room. Normally, I am using skype, slack, Google meet, as well as telegram. Skype: live:.cid.b07d35856decccc8 Gmail: [mykhailoananiev@gmail.com](mailto:mykhailoananiev@gmail.com) Telegram: TerDevil1222
> 
> If you are preferring other messenger, please let me know. And then I will try to contact you on your case messenger.
> 
> I will wait for your reply.
> 
> Regards, Mykhailo
